//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeraOWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FanSoguk
    {
        public int Id { get; set; }
        public Nullable<bool> FanDurum { get; set; }
        public string LimitSicaklik { get; set; }
        public Nullable<bool> FanButonDeger { get; set; }
        public Nullable<int> SeraId { get; set; }
    }
}
