//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeraOWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeraOBitirmeDbv1Entities : DbContext
    {
        public SeraOBitirmeDbv1Entities()
            : base("name=SeraOBitirmeDbv1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatiKapak> CatiKapaks { get; set; }
        public virtual DbSet<Dht11> Dht11 { get; set; }
        public virtual DbSet<FanSoguk> FanSoguks { get; set; }
        public virtual DbSet<HareketSensor> HareketSensors { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<KullaniciRol> KullaniciRols { get; set; }
        public virtual DbSet<Ldr> Ldrs { get; set; }
        public virtual DbSet<LedDurum> LedDurums { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Sensorler> Sensorlers { get; set; }
        public virtual DbSet<Sera> Seras { get; set; }
        public virtual DbSet<SuPompasi> SuPompasis { get; set; }
        public virtual DbSet<TNem> TNems { get; set; }
        public virtual DbSet<ToprakNemKontrol> ToprakNemKontrols { get; set; }
        public virtual DbSet<YagmurSensor> YagmurSensors { get; set; }
        public virtual DbSet<HavalandirmaKontrol> HavalandirmaKontrols { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
