//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeraOWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNem
    {
        public int Id { get; set; }
        public string NemDegeri { get; set; }
        public Nullable<System.DateTime> ETarihi { get; set; }
        public Nullable<int> SeraId { get; set; }
    }
}
